# defaults specify the default config from each component
defaults:

  # dp ref config, inheriting from trainer/config/ref/ref.yaml
  - ref

  # load the reference default config, then apply the fields in the current yaml
  - _self_

# config for FSDP strategy
fsdp_config:

  # whether to offload parameters in FSDP
  param_offload: False

  # whether to perform reshard after model forward to save memory.
  # only for fsdp2, [True, False, int between 1 and fsdp_size]
  reshard_after_forward: True

  # Only for FSDP1: FSDP1 configuration, prefetch the next forward-pass all-gather
  # before the current forward computation.
  forward_prefetch: False

  # the wrap policy for FSDP model
  wrap_policy:

    # minimum number of params in a wrapped module
    min_num_params: 0

# sequence parallel size
# same as actor_rollout_ref.actor.ulysses_sequence_parallel_size if it exists, otherwise 1
ulysses_sequence_parallel_size: ${oc.select:actor_rollout_ref.actor.ulysses_sequence_parallel_size,1}

# calculate entropy with chunking to reduce memory peak
entropy_from_logits_with_chunking: False

# recompute entropy
entropy_checkpointing: False

# Reference model synchronization configuration
# From PR: https://github.com/volcengine/verl/pull/794/files
# Whether to sync reference model with actor model during training
sync_ref_model: False

# Number of forward steps between reference model parameter updates
# Must be > 0 if sync_ref_model is True
ref_model_sync_steps: 0

# Blending coefficient for EMA-style parameter mixing: target = target * (1 - alpha) + source * alpha
# Must be in range (0, 1] if sync_ref_model is True
ref_model_mixup_alpha: 0.0
